### PR TITLE
Refactor, comments, and upgrade to Swift 5

### PR DESCRIPTION
**Pull request by basememara**
Thanks for this, very clever!

### CODE REVIEW

**Comment by caiozullo** [comment]
Hi @basememara, thanks for the PR!

The Swift 5 migration and documentation on the public methods look great, thanks for that! 

I have some questions about other changes. 

1. Can you please explain the reasoning behind all the renamings (methods, protocols, class, params...)? I'd like to keep the names in sync with the YouTube video unless there's a good reason to change.

2. I like the idea of passing the `UIViewController` in the callback `(UIViewController?) -> Void`, but most of our use cases don't need the view controller instance in the callback, that's why we chose  `() -> Void` initially. `() -> Void` simplifies your code a lot when you need to compose with functions that don't take params such as `controller.onViewWillAppear(run: service.reloadItems)` where `reloadItems` don't take any params. So maybe we should have both versions (with and without the UIViewController param) and the clients decide which one they want. And ideally, the one with param should not pass an optional since the `UIViewController` shouldn't invoke the callbacks after deallocation. So `(UIViewController) -> Void` instead.

3. CI is not passing. I believe you need to update the travis.yml with an `osx_image` that supports Swift 5.

Finally, can we break down the contributions into separate PRs? One PR for Swift 5, another for the rest.

Thanks again! ✅

**Comment by basememara** [comment]
Hi @caiozullo,

Thanks for taking a look. Ya sorry I totally went overboard as I meant it as a reference or suggestion. I also figured it was a good time to break the API with Swift 5 upgrade as an excuse :). I have the Swift 5 as PR #2 .

To answer your questions:

1) The name changes were purely suggestion. I felt naming it the same as `viewWillAppear` and letting Swift infer which function, they'd be more easier to discover in autocomplete. However, I did rename `Observer` for good reason because it's so generic and other libraries use it. Since it's public they were all conflicting.

Also, I changed `run` to `execute` to copy some of Apple's conventions like used in `DispatchQueue`.

I do prefer scoping types if they aren't to be used anywhere else. I know `ViewControllerLifecycleObserver` is private, but nesting them seems to make it even more clear that it's only used by this extension. I wish protocols could be nested too (I'm sure you've come across the long thread in the evolution list).

2) I pass in the view controller in the closure callback because sometimes I don't create a local variable before returning the instance. I use a nifty [then](https://github.com/devxoul/Then) extension where it doesn't require me to create local variables all the time, so I can do this:
```
func showList() -> UIViewController {
    return ShowListViewController(...).then {
         $0?.onViewWillAppear {
               // Do something
          }
    }
}
```
I can't think of examples without this `then` library, but figured this wouldn't force callers to create a local variable to use the controller within the closure, also kind of in line with Apple convention and how they pass back the instance in delegates all the time.

I really wanted to make it non-optional, but I was trying to avoid to create a weak reference within `ViewControllerLifecycleObserver` to store the controller instance, so I was using the native `parent` property to pass back in the closure.

3) I updated the `.travis` file. I wasn't sure how to check if it worked before creating the PR. I'll try to fix it again if it's a problem.

Feel free to close this PR just for documentation purposes maybe to spark some ideas later.

Thanks again for the library and the feedback.

**Comment by caiozullo** [comment]
1. `execute` sounds better than `run` especially since it's a convention in some Apple APIs ✅

2. In my opinion, `controller.onViewWillAppear(execute:)` reads better than `controller.viewWillAppear(execute:)`.

3. Regarding the `Observer` name conflicts: Ideally, you should import this project as a framework, so the module namespace should solve the conflicts. (module).(type) as in `ViewControllerLifecycleObservers.Observer`. 

4. We can't nest protocols, but alternatively, since there's only one method in the protocol we could replace it with a closure `() -> Void` and use a nested `typealias` within the extension. For example:

```
public extension UIViewControler {
    public typealias Observer = () -> Void

    @discardableResult
    public func onViewWillAppear(run callback: @escaping () -> Void) -> LifecycleObserver {
        return ViewControllerLifecycleObserver(
            parent: self,
            viewWillAppearCallback: callback
        ).remove
    }
}

let unsubscribe = controller.onViewWillAppear(run: service.reloadItems)
unsubscribe()
```

However, I'm not sure nesting types would solve the naming conflict problem since they'd be nested inside a UIKit type, the `UIViewController`. We can still have conflicts with `UIViewControler.Observer` since other libraries may use the same name. Module scope sounds like a safer bet to me.

5. I agree with passing the view controller to the closure as I've run in some use cases where that would come in handy. However, I still believe it should be a separate API since many use cases are just interested in the events, not the view controller instance. Having both options would be great!

6. To avoid the optional, I believe you could check for the `parent` existence before calling the callback. Something like `parent.map(callback)`. Does it make sense to execute the closure if the `parent` is `nil`?

Thanks again for the ideas!

**Comment by basememara** [comment]
Ohh I like the `typealias` idea. It is fortunate that it's just one method.

Also I think I found a good way to create a separate callback in PR #3. The test passes for this. See what you think or if there could be a less verbose way than duplicating all the functions (was better than duplicating all the closure properties  of `ViewControllerLifecycleObserver ` tho). What I was looking for was default parameters in closure arguments which doesn't exist in Swift.

**Comment by caiozullo** [comment]
Cool, closing this one then.

**Pull request closed without merging**
